#!/bin/bash
timedatectl set-ntp 1
sudo pacman -S openbox ttf-dejavu ttf-liberation nitrogen obconf dmenu menumaker nemo xfce-session lightdm lightdm-gtk-greeter xfce-terminal xfce-settings

sudo cp /etc/X11/xinit/xinitrc ~/.xinitrc

tar -xf archive.tar -C /home/$user
mmaker openbox3


